# Generated by Django 5.2.5 on 2025-08-21 06:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='acquisition_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
